services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - jobportal-network

  config-server:
    build: ./config-server
    ports:
      - "2222:2222"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    networks:
      - jobportal-network
    depends_on:
      - discovery-server

  api-gateway:
    build: ./api-gateway
    ports:
      - "2020:2020"
    command: ["--eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/"]
    env_file:
      - .env
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:2222
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    networks:
      - jobportal-network
    depends_on:
      - config-server
      - discovery-server

  identity-service:
    build: ./identity-service
    ports:
      - "2021:2021"
    command: ["--eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/"]
    env_file:
      - .env
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:2222
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    networks:
      - jobportal-network
    depends_on:
      - config-server
      - discovery-server

  job-service:
    build: ./job-service
    ports:
      - "2022:2022"
    command: ["--eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/"]
    env_file:
      - .env
    environment:
      - SERVER_PORT=2022
      - SPRING_DATA_MONGODB_URI=${MONGO_JOB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:2222
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    networks:
      - jobportal-network
    depends_on:
      - config-server
      - discovery-server

  application-service:
    build: ./application-service
    ports:
      - "2024:2024"
    command: [ "--eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/" ]
    env_file:
      - .env
    environment:
      - SERVER_PORT=2024
      - SPRING_DATA_MONGODB_URI=${MONGO_APPLICATION_URI:-${MONGO_JOB_URI}} # Falls back to job DB if app DB isn't set
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:2222
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - jobportal-network
    depends_on:
      - config-server
      - discovery-server

  notification-service:
    build: ./notification-service
    ports:
      - "2025:2025"
    command: [ "--eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/" ]
    env_file:
      - .env
    environment:
      - SERVER_PORT=2025
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:2222
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - jobportal-network
    depends_on:
      - config-server
      - discovery-server
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - jobportal-network

  kafka:
      image: confluentinc/cp-kafka:7.6.0
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        # 29092 is for internal Docker traffic, 9092 is so your local IntelliJ can reach it!
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      networks:
        - jobportal-network

networks:
  jobportal-network:
    driver: bridge