spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**
          filters:
            - AuthenticationFilter

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profiles/**

        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/applications/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}
  instance:
    preferIpAddress: true

jwt:
  secret: ${JWT_SECRET}