spring:
  data:
    mongodb:
      uri: ${MONGO_APPLICATIONS_URI}
  kafka:
    bootstrap-servers: kafka:29092 # Connects to the internal Docker Kafka network
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true