name: Microservices CI Pipeline

# to push code for every commit
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    # to run a new Ubuntu server hosted by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your code onto the GitHub server
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2: Install the correct version of Java
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven # This caches your dependencies so future builds are super fast!

      # Step 3: Run the Maven build command across all 5 services
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests